// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://postgres.jnqalvmlyzahtxyhafhw:Hacobo258%21%3F@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres",
  },
});
