import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { generateAuraPlaylistCover } from "@/lib/playlist-cover";
import { SpotifyClient, SpotifyAPIError, type SpotifyPlaylist } from "@/lib/spotify/client";
import { checkRateLimit } from "@/lib/rate-limiter";

export const maxDuration = 60;
export const runtime = "nodejs";

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.accessToken || !session.spotifyId) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const rl = await checkRateLimit(`user:${session.spotifyId}`, "playlist");
  if (!rl.allowed) {
    return Response.json(
      { error: `Rate limit exceeded. Try again after ${new Date(rl.resetAt).toLocaleTimeString()}.` },
      { status: 429, headers: { "Retry-After": String(Math.ceil((rl.resetAt - Date.now()) / 1000)) } }
    );
  }

  try {
    const body = await req.json();
    const { shareId } = body;

    if (!shareId) {
      return Response.json({ error: "Missing shareId" }, { status: 400 });
    }

    // Look up the user's DB id from their Spotify ID
    const user = await db.user.findUnique({ where: { spotifyId: session.spotifyId } });
    if (!user) {
      return Response.json({ error: "User not found" }, { status: 404 });
    }

    const shareCard = await db.shareCard.findUnique({
      where: { id: shareId },
    });

    if (!shareCard || shareCard.userId !== user.id) {
      return Response.json({ error: "Share card not found or unauthorized" }, { status: 404 });
    }

    const client = new SpotifyClient(session.accessToken as string);

    // Check scopes — required for playlist creation
    const grantedScopes = (session.scope ?? "").split(" ").filter(Boolean);

    const hasPlaylistScope =
      grantedScopes.includes("playlist-modify-public") ||
      grantedScopes.includes("playlist-modify-private");
    const hasCoverUploadScope = grantedScopes.includes("ugc-image-upload");

    if (!hasPlaylistScope) {
      console.error("[export-playlist] Missing playlist scopes. Session scope string:", session.scope ?? "(null)");
      return Response.json({
        error: "REAUTH_REQUIRED",
        message: "Your session is missing playlist permissions. Please sign out and sign back in to grant Melo permission to create playlists.",
      }, { status: 403 });
    }

    // Collect track URIs — prefer live Spotify fetch for freshest data
    let uris: string[] = [];

    // Strategy 1: Fetch the user's actual top tracks live (most reliable)
    try {
      const timeRange = (shareCard.timeRange ?? "medium_term") as "short_term" | "medium_term" | "long_term";
      const topTracksRes = await client.getTopTracks(timeRange, 50);
      if (topTracksRes?.items?.length > 0) {
        uris = topTracksRes.items.map(t => `spotify:track:${t.id}`);
      }
    } catch (err) {
      console.warn("[export-playlist] Live top tracks fetch failed, falling back to snapshot:", err instanceof SpotifyAPIError ? `${err.status} ${err.message}` : err);
    }

    // Strategy 2: Fall back to stored snapshot if live fetch returned nothing
    if (uris.length === 0) {
      const topTracks = shareCard.topTracks as Array<{ id: string }> | null;
      if (topTracks && Array.isArray(topTracks)) {
        uris = topTracks.filter(t => t?.id).map(t => `spotify:track:${t.id}`);
      }
    }

    const batch = [...new Set(uris)].slice(0, 100);
    if (batch.length === 0) {
      console.warn("[export-playlist] No tracks found; skipping playlist creation");
      return Response.json({
        error: "No tracks found for this aura. Please refresh your analysis and try again.",
      }, { status: 422 });
    }

    // Create the playlist using Spotify's current documented endpoint.
    const playlistName = `${shareCard.moodTitle || shareCard.auraColor} Aura · Melo`;
    const playlistDesc = `Your ${shareCard.auraColor} aura playlist, generated by Melo. "${shareCard.tagline}"`;

    let playlist: SpotifyPlaylist;
    try {
      playlist = await client.createPlaylist(playlistName, playlistDesc, false);
    } catch (err) {
      console.error("[export-playlist] createPlaylist failed:", err);
      if (err instanceof SpotifyAPIError) {
        console.error(`  → Spotify status: ${err.status}, message: ${err.message}`);
        if (err.status === 403) {
          // 403 from Spotify usually means either:
          // 1. The app is in Development Mode and the user is NOT on the allowlist
          //    → Fix: Go to Spotify Developer Dashboard > Users and Access > Add your Spotify email
          // 2. The access token doesn't actually have the playlist modify scopes
          //    → Fix: Sign out, then sign back in to get a fresh token with correct scopes
          console.error("[export-playlist] 403 from Spotify. Granted scopes:", grantedScopes.join(", "));
          console.error("[export-playlist] This is usually caused by the app being in Development Mode.");
          console.error("[export-playlist] Add the user's Spotify email to the allowlist at:");
          console.error("[export-playlist] https://developer.spotify.com/dashboard → Your App → Settings → User Management");
          return Response.json({
            error: "REAUTH_REQUIRED",
            message: "Spotify refused to create the playlist (403). Your app may be in Development Mode — add your Spotify account email to the allowlist in the Spotify Developer Dashboard under Settings > User Management.",
          }, { status: 403 });
        }
        return Response.json({ error: err.message }, { status: err.status });
      }
      return Response.json({ error: "Failed to create playlist" }, { status: 500 });
    }




    // Add tracks if we have any
    // Brief delay — Spotify sometimes needs a moment before a new playlist is writable
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Spotify accepts max 100 per request — we cap at 100 and use replacePlaylistTracks (PUT).
    let lastErr: unknown;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        await client.replacePlaylistTracks(playlist.id, batch);
        lastErr = undefined;
        break;
      } catch (err) {
        lastErr = err;
        console.warn(`[export-playlist] Attempt ${attempt} failed:`, err instanceof SpotifyAPIError ? `${err.status} ${err.message}` : err);
        if (attempt < 3) await new Promise(resolve => setTimeout(resolve, attempt * 1000));
      }
    }
    if (lastErr) throw lastErr; // re-throw after all retries exhausted

    let coverUploaded = false;
    let coverUploadSkippedReason: string | undefined;
    if (hasCoverUploadScope) {
      try {
        const coverBase64 = await generateAuraPlaylistCover({
          moodTitle: shareCard.moodTitle || "Melo Aura",
          auraColor: shareCard.auraColor,
          tagline: shareCard.tagline,
        });
        await client.uploadPlaylistCoverImage(playlist.id, coverBase64);
        coverUploaded = true;
      } catch (err) {
        coverUploadSkippedReason = err instanceof SpotifyAPIError
          ? `Spotify cover upload failed (${err.status}): ${err.message}`
          : "Cover generation failed";
        console.warn("[export-playlist] Cover upload skipped:", err);
      }
    } else {
      coverUploadSkippedReason = "Missing ugc-image-upload scope. Sign out and sign back in to enable custom playlist covers.";
      console.warn("[export-playlist] Cover upload skipped: missing ugc-image-upload scope");
    }

    const playlistUrl = playlist.external_urls?.spotify ?? `https://open.spotify.com/playlist/${playlist.id}`;
    return Response.json({
      success: true,
      url: playlistUrl,
      playlistId: playlist.id,
      trackCount: batch.length,
      coverUploaded,
      coverUploadSkippedReason,
    });
  } catch (err) {
    console.error("Failed to export playlist:", err);
    // Surface specific Spotify errors to the client
    if (err instanceof SpotifyAPIError) {
      console.error(`[export-playlist] Spotify error ${err.status}: ${err.message}`);
      return Response.json({ error: `Spotify error (${err.status}): ${err.message}` }, { status: err.status });
    }
    return Response.json({ error: "An unexpected error occurred. Please try again." }, { status: 500 });
  }
}
